/* Generated by: ParserGeneratorCC: Do not edit this line. TokenManager.java Version 1.1 */
/* ParserGeneratorCCOptions:SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
/**
 * An implementation for this interface is generated by
 * JavaCCParser.  The user is free to use any implementation
 * of their choice.
 */
public interface TokenManager {
  /** This gets the next token from the input stream.
   *  A token of kind 0 (&lt;EOF&gt;) should be returned on EOF.
   *  @return the next Token. Should not be <code>null</code>.
   */
  Token getNextToken();
}
/* ParserGeneratorCC - OriginalChecksum=85cc1f10c138343298562878bad296c8 (do not edit this line) */
